name: project-test-sonar-scanner-workflow
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.x 
      - name: Run Testing
        run: dotnet test